services:
  db:
    image: postgres:17.5-alpine
    container_name: api_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: api
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - baibusu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  drizzle-push:
    build:
      context: .
      target: dev-deps   # Use dev stage to include drizzle-kit
    working_dir: /app
    command:
    - sh
    - -c
    - |
      sleep 2
      pnpm exec drizzle-kit push --force --config drizzle.config.ts
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - baibusu

  api:
    image: honoapi:latest  # or build: ./ for prod
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      drizzle-push:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    networks:
      - baibusu
    healthcheck:
      test: "curl -s -I http://localhost:3000 | head -n 1 | grep 200"
      interval: 15s
      timeout: 1m
      retries: 3
      start_period: 30s

volumes:
  pg_data:

networks:
  baibusu:
    external: true